const fs = require('fs');

let idCounter = 1;
const tests = [];
function add(ref, type, actor, p, risk, title, pre, steps, exp, fail) {
  tests.push({
    id: 'tc_' + String(idCounter++).padStart(3, '0'),
    title,
    scope: ref.startsWith('flow') ? 'flow' : 'feature',
    scope_ref: ref,
    actor,
    priority: p,
    risk,
    type,
    precondition: pre,
    steps: steps.split('|').map((s,i) => `${i+1}. ${s}`),
    expected_result: exp,
    failure_indicator: fail
  });
}

const data = [
  ["feat_usr_auth_register", "happy_path", "unauthenticated", "P1-critical", "high", "Valid reg", "None", "Go /register|Fill details|Submit", "Account created", "Error shown"],
  ["feat_usr_auth_register", "error_case", "unauthenticated", "P2-high", "medium", "Dup email", "Email exists", "Go /register|Fill existing email|Submit", "Error msg", "Created"],
  ["feat_usr_auth_register", "auth_boundary", "user", "P2-high", "medium", "Logged in", "Logged in", "Go /register", "Redirected", "Page loads"],
  ["feat_usr_auth_login", "happy_path", "unauthenticated", "P1-critical", "high", "Valid login", "Has account", "Go /login|Enter creds|Submit", "Logged in", "Fails"],
  ["feat_usr_auth_login", "error_case", "unauthenticated", "P2-high", "medium", "Wrong pass", "Has account", "Go /login|Enter wrong pass|Submit", "Error msg", "Logs in"],
  ["feat_usr_auth_login", "auth_boundary", "user", "P2-high", "medium", "Logged in", "Logged in", "Go /login", "Redirected", "Page loads"],
  ["feat_usr_auth_logout", "happy_path", "user", "P1-critical", "high", "Logout", "Logged in", "Click logout", "Session ends", "Stays logged in"],
  ["feat_usr_auth_logout", "error_case", "user", "P3-medium", "low", "Fast click", "Logged in", "Double click logout", "Logs out safely", "Crash"],
  ["feat_usr_auth_logout", "auth_boundary", "unauthenticated", "P2-high", "medium", "No session", "Logged out", "Call logout API", "401 error", "200 OK"],
  ["feat_usr_profile_view", "happy_path", "user", "P2-high", "medium", "View profile", "Logged in", "Go /profile", "Data shown", "Empty/Error"],
  ["feat_usr_profile_view", "error_case", "user", "P3-medium", "low", "Server slow", "Logged in", "Simulate delay", "Loading state", "Crash"],
  ["feat_usr_profile_view", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth access", "Logged out", "Go /profile", "Redirect login", "Data shown"],
  ["feat_usr_profile_update", "happy_path", "user", "P2-high", "medium", "Update name", "Logged in", "Go /profile|Change name|Save", "Updated", "Fails"],
  ["feat_usr_profile_update", "error_case", "user", "P3-medium", "low", "Invalid phone", "Logged in", "Enter letters in phone|Save", "Validation error", "Saved"],
  ["feat_usr_profile_update", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth API", "Logged out", "POST /api/auth/me", "401 error", "200 OK"],
  ["feat_usr_change_password", "happy_path", "user", "P2-high", "high", "Change pass", "Logged in", "Enter old pass|Enter new|Save", "Pass updated", "Fails"],
  ["feat_usr_change_password", "error_case", "user", "P3-medium", "low", "Wrong old", "Logged in", "Enter wrong old pass|Save", "Error msg", "Updated"],
  ["feat_usr_change_password", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth API", "Logged out", "POST change-pass", "401 error", "200 OK"],
  ["feat_usr_shipping_crud", "happy_path", "user", "P2-high", "medium", "Add address", "Logged in", "Click add|Fill info|Save", "Saved", "Fails"],
  ["feat_usr_shipping_crud", "error_case", "user", "P3-medium", "low", "Missing field", "Logged in", "Omit city|Save", "Validation error", "Saved"],
  ["feat_usr_shipping_crud", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth access", "Logged out", "Access shipping API", "401 error", "200 OK"],
  ["feat_usr_prod_list", "happy_path", "unauthenticated", "P2-high", "medium", "View list", "None", "Go /products", "List loads", "Empty/Error"],
  ["feat_usr_prod_list", "error_case", "unauthenticated", "P3-medium", "low", "Bad page", "None", "Go /products?page=999", "Empty state", "Crash"],
  ["feat_usr_prod_search", "happy_path", "unauthenticated", "P2-high", "medium", "Search valid", "None", "Type 'shirt'", "Results match", "No results"],
  ["feat_usr_prod_search", "error_case", "unauthenticated", "P3-medium", "low", "Search special", "None", "Type '###'", "Empty state", "Crash"],
  ["feat_usr_prod_special", "happy_path", "unauthenticated", "P3-medium", "low", "View hot", "None", "Go homepage", "Hot items show", "Missing"],
  ["feat_usr_prod_special", "error_case", "unauthenticated", "P4-low", "low", "Empty hot", "No DB data", "Go homepage", "Hidden/Empty msg", "Crash"],
  ["feat_usr_prod_detail", "happy_path", "unauthenticated", "P1-critical", "high", "View detail", "Product exists", "Click product", "Detail page loads", "Error"],
  ["feat_usr_prod_detail", "error_case", "unauthenticated", "P2-high", "medium", "Invalid slug", "None", "Go /products/invalid", "404 page", "Crash"],
  ["feat_usr_cat_list", "happy_path", "unauthenticated", "P2-high", "medium", "View cats", "None", "Go /category", "Categories show", "Error"],
  ["feat_usr_cat_list", "error_case", "unauthenticated", "P4-low", "low", "Empty cats", "DB empty", "Go /category", "Empty state", "Crash"],
  ["feat_usr_brand_list", "happy_path", "unauthenticated", "P2-high", "medium", "View brands", "None", "Go /brands", "Brands show", "Error"],
  ["feat_usr_brand_list", "error_case", "unauthenticated", "P4-low", "low", "Empty brands", "DB empty", "Go /brands", "Empty state", "Crash"],
  ["feat_usr_camp_view", "happy_path", "unauthenticated", "P2-high", "medium", "View campaigns", "Active campaign", "Go /campaigns", "Campaigns show", "Error"],
  ["feat_usr_camp_view", "error_case", "unauthenticated", "P4-low", "low", "No active", "None active", "Go /campaigns", "Empty state", "Crash"],
  ["feat_usr_vouch_active", "happy_path", "unauthenticated", "P2-high", "medium", "View vouchers", "Active voucher", "Go /vouchers", "Vouchers show", "Error"],
  ["feat_usr_vouch_active", "error_case", "unauthenticated", "P4-low", "low", "No active", "None active", "Go /vouchers", "Empty state", "Crash"],
  ["feat_usr_cart_manage", "happy_path", "user", "P1-critical", "high", "Add to cart", "Logged in", "Click add to cart", "Item added", "Fails"],
  ["feat_usr_cart_manage", "error_case", "user", "P2-high", "medium", "Exceed stock", "Logged in", "Add qty > stock", "Error msg", "Added"],
  ["feat_usr_cart_manage", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth add", "Logged out", "Click add to cart", "Redirect login", "Added"],
  ["feat_usr_vouch_apply", "happy_path", "user", "P2-high", "high", "Apply valid", "Logged in", "Enter valid code|Apply", "Discount applied", "Fails"],
  ["feat_usr_vouch_apply", "error_case", "user", "P2-high", "medium", "Apply expired", "Logged in", "Enter expired code|Apply", "Error msg", "Applied"],
  ["feat_usr_vouch_apply", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth apply", "Logged out", "API apply voucher", "401 error", "200 OK"],
  ["feat_usr_ord_preview", "happy_path", "user", "P1-critical", "high", "Preview cart", "Logged in", "Go /checkout", "Preview loads", "Fails"],
  ["feat_usr_ord_preview", "error_case", "user", "P2-high", "medium", "Out of stock", "Logged in", "Go /checkout with OOS item", "Warning msg", "Proceeds"],
  ["feat_usr_ord_preview", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth preview", "Logged out", "Go /checkout", "Redirect login", "Loads"],
  ["feat_usr_ord_place", "happy_path", "user", "P1-critical", "high", "Place order", "Logged in", "Click place order", "Order created", "Fails"],
  ["feat_usr_ord_place", "error_case", "user", "P2-high", "high", "Empty cart", "Logged in", "Place empty cart", "Error msg", "Created"],
  ["feat_usr_ord_place", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth place", "Logged out", "API checkout", "401 error", "200 OK"],
  ["feat_usr_ord_list", "happy_path", "user", "P2-high", "medium", "View orders", "Logged in", "Go /orders", "List loads", "Fails"],
  ["feat_usr_ord_list", "error_case", "user", "P4-low", "low", "No orders", "Logged in", "Go /orders", "Empty state", "Crash"],
  ["feat_usr_ord_list", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth view", "Logged out", "Go /orders", "Redirect login", "Loads"],
  ["feat_usr_ord_detail", "happy_path", "user", "P2-high", "medium", "View detail", "Logged in", "Click order", "Detail loads", "Fails"],
  ["feat_usr_ord_detail", "error_case", "user", "P2-high", "high", "View others", "Logged in", "Go other user order ID", "403 error", "Loads"],
  ["feat_usr_ord_detail", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth detail", "Logged out", "Go /orders/1", "Redirect login", "Loads"],
  ["feat_usr_ord_cancel", "happy_path", "user", "P1-critical", "high", "Cancel pending", "Logged in", "Click cancel on pending", "Cancelled", "Fails"],
  ["feat_usr_ord_cancel", "error_case", "user", "P2-high", "high", "Cancel shipped", "Logged in", "API cancel shipped", "Error msg", "Cancelled"],
  ["feat_usr_ord_cancel", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth cancel", "Logged out", "API cancel", "401 error", "200 OK"],
  ["feat_usr_prod_related", "happy_path", "unauthenticated", "P3-medium", "low", "View related", "Product exists", "View product", "Related show", "Empty"],
  ["feat_usr_prod_related", "error_case", "unauthenticated", "P4-low", "low", "No related", "Unique category", "View product", "Empty/Hidden", "Crash"],
  ["feat_usr_buy_now", "happy_path", "user", "P1-critical", "high", "Buy direct", "Logged in", "Click Buy Now", "Go checkout", "Fails"],
  ["feat_usr_buy_now", "error_case", "user", "P2-high", "medium", "Buy OOS", "Logged in", "Click Buy Now on OOS", "Error msg", "Proceeds"],
  ["feat_usr_buy_now", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth buy", "Logged out", "Click Buy Now", "Redirect login", "Proceeds"],
  ["feat_usr_homepage", "happy_path", "unauthenticated", "P2-high", "medium", "View home", "None", "Go /", "Home loads", "Error"],
  ["feat_usr_homepage", "error_case", "unauthenticated", "P3-medium", "low", "API slow", "None", "Simulate slow API", "Loading state", "Crash"],
  ["feat_usr_prod_filter", "happy_path", "unauthenticated", "P2-high", "medium", "Filter price", "None", "Set price range", "List updates", "Fails"],
  ["feat_usr_prod_filter", "error_case", "unauthenticated", "P3-medium", "low", "Min > Max", "None", "Set min 100 max 10", "Validation error", "Crash"],
  ["feat_usr_shipping_default", "happy_path", "user", "P2-high", "medium", "Set default", "Logged in", "Click set default", "Updated", "Fails"],
  ["feat_usr_shipping_default", "error_case", "user", "P3-medium", "low", "Invalid ID", "Logged in", "API set default 999", "Error msg", "Success"],
  ["feat_usr_shipping_default", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth set", "Logged out", "API set default", "401 error", "200 OK"],
  ["feat_adm_dash_view", "happy_path", "admin", "P2-high", "medium", "View dash", "Admin in", "Go /admin", "Stats load", "Fails"],
  ["feat_adm_dash_view", "error_case", "admin", "P3-medium", "low", "Bad dates", "Admin in", "Filter invalid dates", "Error msg", "Crash"],
  ["feat_adm_dash_view", "auth_boundary", "user", "P1-critical", "high", "User access", "User in", "Go /admin", "403 error", "Loads"],
  ["feat_adm_prod_crud", "happy_path", "admin", "P1-critical", "high", "Create prod", "Admin in", "Fill product|Save", "Created", "Fails"],
  ["feat_adm_prod_crud", "error_case", "admin", "P2-high", "medium", "Missing name", "Admin in", "Save empty form", "Validation", "Created"],
  ["feat_adm_prod_crud", "auth_boundary", "user", "P1-critical", "high", "User create", "User in", "API POST product", "403 error", "200 OK"],
  ["feat_adm_prod_img", "happy_path", "admin", "P2-high", "medium", "Upload img", "Admin in", "Select image|Upload", "Uploaded", "Fails"],
  ["feat_adm_prod_img", "error_case", "admin", "P3-medium", "low", "Upload PDF", "Admin in", "Select PDF|Upload", "Validation", "Uploaded"],
  ["feat_adm_prod_img", "auth_boundary", "user", "P1-critical", "high", "User upload", "User in", "API upload img", "403 error", "200 OK"],
  ["feat_adm_prod_var_crud", "happy_path", "admin", "P2-high", "medium", "Add var", "Admin in", "Fill variant|Save", "Added", "Fails"],
  ["feat_adm_prod_var_crud", "error_case", "admin", "P3-medium", "low", "Neg price", "Admin in", "Set price -10|Save", "Validation", "Saved"],
  ["feat_adm_prod_var_crud", "auth_boundary", "user", "P1-critical", "high", "User add", "User in", "API add var", "403 error", "200 OK"],
  ["feat_adm_cat_crud", "happy_path", "admin", "P2-high", "medium", "Add cat", "Admin in", "Fill cat|Save", "Created", "Fails"],
  ["feat_adm_cat_crud", "error_case", "admin", "P3-medium", "low", "Dup cat", "Admin in", "Save existing name", "Error msg", "Created"],
  ["feat_adm_cat_crud", "auth_boundary", "user", "P1-critical", "high", "User add cat", "User in", "API add cat", "403 error", "200 OK"],
  ["feat_adm_brand_crud", "happy_path", "admin", "P2-high", "medium", "Add brand", "Admin in", "Fill brand|Save", "Created", "Fails"],
  ["feat_adm_brand_crud", "error_case", "admin", "P3-medium", "low", "Dup brand", "Admin in", "Save existing name", "Error msg", "Created"],
  ["feat_adm_brand_crud", "auth_boundary", "user", "P1-critical", "high", "User add brand", "User in", "API add brand", "403 error", "200 OK"],
  ["feat_adm_vouch_crud", "happy_path", "admin", "P2-high", "high", "Add vouch", "Admin in", "Fill vouch|Save", "Created", "Fails"],
  ["feat_adm_vouch_crud", "error_case", "admin", "P2-high", "medium", "End < Start", "Admin in", "Set dates wrong|Save", "Validation", "Created"],
  ["feat_adm_vouch_crud", "auth_boundary", "user", "P1-critical", "high", "User add vouch", "User in", "API add vouch", "403 error", "200 OK"],
  ["feat_adm_ord_manage", "happy_path", "admin", "P1-critical", "high", "Update status", "Admin in", "Change status|Save", "Updated", "Fails"],
  ["feat_adm_ord_manage", "error_case", "admin", "P2-high", "high", "Invalid transition", "Admin in", "API pending to delivered", "Error msg", "Updated"],
  ["feat_adm_ord_manage", "auth_boundary", "user", "P1-critical", "high", "User update", "User in", "API update ord", "403 error", "200 OK"],
  ["feat_adm_camp_crud", "happy_path", "admin", "P2-high", "high", "Add camp", "Admin in", "Fill camp|Save", "Created", "Fails"],
  ["feat_adm_camp_crud", "error_case", "admin", "P3-medium", "low", "No items", "Admin in", "Save without items", "Validation", "Created"],
  ["feat_adm_camp_crud", "auth_boundary", "user", "P1-critical", "high", "User add camp", "User in", "API add camp", "403 error", "200 OK"],
  ["feat_adm_ord_bulk", "happy_path", "admin", "P2-high", "medium", "Bulk update", "Admin in", "Select multi|Update", "Updated", "Fails"],
  ["feat_adm_ord_bulk", "error_case", "admin", "P2-high", "medium", "Mixed states", "Admin in", "Select invalid ones", "Partial/Error", "Updated all"],
  ["feat_adm_ord_bulk", "auth_boundary", "user", "P1-critical", "high", "User bulk", "User in", "API bulk update", "403 error", "200 OK"],
  ["feat_adm_ord_filter", "happy_path", "admin", "P3-medium", "low", "Filter ord", "Admin in", "Select status", "List filtered", "Fails"],
  ["feat_adm_ord_filter", "error_case", "admin", "P3-medium", "low", "Bad query", "Admin in", "API status=XYZ", "Error msg", "Crash"],
  ["feat_adm_ord_filter", "auth_boundary", "user", "P1-critical", "high", "User filter", "User in", "API filter ord", "403 error", "200 OK"],
  ["feat_adm_camp_status", "happy_path", "admin", "P2-high", "medium", "Toggle camp", "Admin in", "Click toggle", "Toggled", "Fails"],
  ["feat_adm_camp_status", "error_case", "admin", "P3-medium", "low", "Toggle expired", "Admin in", "Toggle ended camp", "Error msg", "Toggled"],
  ["feat_adm_camp_status", "auth_boundary", "user", "P1-critical", "high", "User toggle", "User in", "API toggle camp", "403 error", "200 OK"],
  ["feat_adm_auth_guard", "happy_path", "admin", "P1-critical", "high", "Admin token", "Admin in", "Access API", "200 OK", "403 error"],
  ["feat_adm_auth_guard", "error_case", "admin", "P2-high", "high", "Expired token", "Admin token exp", "Access API", "401 error", "200 OK"],
  ["feat_adm_auth_guard", "auth_boundary", "unauthenticated", "P1-critical", "high", "No token", "Logged out", "Access API", "401 error", "200 OK"],
  ["feat_sys_ai_desc", "happy_path", "system", "P3-medium", "low", "Gen AI", "Admin edits", "Click Gen AI", "Desc filled", "Fails"],
  ["feat_sys_ai_desc", "error_case", "system", "P3-medium", "low", "API Down", "Admin edits", "Simulate Groq down", "Error msg", "Crash"],
  ["feat_sys_email_notif", "happy_path", "system", "P2-high", "medium", "Send email", "Order placed", "Check inbox", "Email received", "Fails"],
  ["feat_sys_email_notif", "error_case", "system", "P3-medium", "low", "SMTP fail", "Order placed", "Simulate SMTP down", "Order still OK", "Order fails"],
  ["feat_sys_img_upload", "happy_path", "system", "P2-high", "medium", "Upload Cloud", "File picked", "Upload API", "URL returned", "Fails"],
  ["feat_sys_img_upload", "error_case", "system", "P3-medium", "low", "Too large", "File picked", "Upload 20MB", "Error msg", "Uploaded"],
  ["feat_sys_jwt_refresh", "happy_path", "system", "P1-critical", "high", "Auto refresh", "Token expired", "Make API call", "New token got", "Logout"],
  ["feat_sys_jwt_refresh", "error_case", "system", "P1-critical", "high", "Bad refresh", "Refresh exp", "Make API call", "Forced logout", "Stuck"],
  ["feat_sys_stock_guard", "happy_path", "system", "P1-critical", "high", "Stock dec", "Checkout", "Place order", "Stock reduced", "Unchanged"],
  ["feat_sys_stock_guard", "error_case", "system", "P1-critical", "high", "Race cond", "Checkout", "Concurrent checkout", "Rollback one", "Negative stock"],
  ["feat_sys_campaign_engine", "happy_path", "system", "P1-critical", "high", "Calc best", "Cart loaded", "Preview checkout", "Best disc applied", "Wrong disc"],
  ["feat_sys_campaign_engine", "error_case", "system", "P2-high", "high", "Item removed", "Cart loaded", "Remove req item", "Disc removed", "Disc stays"],
  ["feat_sys_voucher_engine", "happy_path", "system", "P1-critical", "high", "Calc vouch", "Apply vouch", "Preview checkout", "Vouch applied", "Fails"],
  ["feat_sys_voucher_engine", "error_case", "system", "P2-high", "high", "Under min", "Apply vouch", "Reduce cart val", "Vouch rejected", "Vouch stays"],
  ["feat_sys_price_change_detect", "happy_path", "system", "P2-high", "medium", "Detect change", "Price changed", "Preview checkout", "Warning shown", "Silent"],
  ["feat_sys_price_change_detect", "error_case", "system", "P3-medium", "low", "Item deleted", "Item deleted", "Preview checkout", "Removed msg", "Crash"],
  ["feat_sys_sku_autogen", "happy_path", "system", "P3-medium", "low", "Gen SKU", "Add var empty", "Save variant", "SKU generated", "Empty"],
  ["feat_sys_sku_autogen", "error_case", "system", "P4-low", "low", "Collision", "Add var empty", "Force collision", "Appends random", "Error"],
  ["feat_sys_order_snapshot", "happy_path", "system", "P2-high", "high", "Snapshot", "Order placed", "Change prod price", "Order price same", "Price changes"],
  ["feat_sys_order_snapshot", "error_case", "system", "P3-medium", "low", "DB Error", "Order placed", "Simulate DB err", "Order rollbacks", "Half saved"],
  ["flow_001", "happy_path", "user", "P1-critical", "high", "Purchase Flow", "None", "View|Add|Apply|Preview|Place|Email|Fulfill", "Completed", "Stuck"],
  ["flow_001", "error_case", "user", "P2-high", "medium", "Cart Fail", "None", "View|Add OOS|Stop", "Stopped safely", "Proceeds empty"],
  ["flow_001", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth Flow", "None", "View|Add|Checkout", "Login redirect", "Proceeds"],
  ["flow_002", "happy_path", "admin", "P1-critical", "high", "Create Prod Flow", "Admin in", "Info|AI|Img|Var|Active", "Active prod", "Fails"],
  ["flow_002", "error_case", "admin", "P2-high", "medium", "AI Fail Flow", "Admin in", "Info|AI Fails|Manual", "Saved", "Crash"],
  ["flow_002", "auth_boundary", "user", "P1-critical", "high", "User Flow 2", "User in", "Start Flow 002", "403 error", "Proceeds"],
  ["flow_003", "happy_path", "user", "P1-critical", "high", "Cancel Flow", "Order pend", "List|Cancel|Email", "Cancelled", "Fails"],
  ["flow_003", "error_case", "user", "P2-high", "medium", "Cancel Ship", "Order ship", "List|Try Cancel", "Hidden/Error", "Cancelled"],
  ["flow_003", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth Cancel", "Logged out", "API Cancel", "401 error", "200 OK"],
  ["flow_004", "happy_path", "admin", "P2-high", "high", "Camp Flow", "Admin in", "New|Info|AI|Submit|Active", "Active camp", "Fails"],
  ["flow_004", "error_case", "admin", "P3-medium", "low", "Camp AI Fail", "Admin in", "New|AI Fail|Manual", "Saved", "Crash"],
  ["flow_004", "auth_boundary", "user", "P1-critical", "high", "User Camp", "User in", "Start Flow 004", "403 error", "Proceeds"],
  ["flow_005", "happy_path", "unauthenticated", "P1-critical", "high", "Reg to Buy", "None", "Reg|Login|Home|Ship|Cart|Place|Email", "Completed", "Fails"],
  ["flow_005", "error_case", "unauthenticated", "P2-high", "medium", "Reg Fail", "None", "Reg Bad|Stop", "Handled", "Crash"],
  ["flow_005", "auth_boundary", "user", "P2-high", "medium", "Already Reg", "Logged in", "Reg again", "Redirect", "Page loads"],
  ["flow_006", "happy_path", "user", "P1-critical", "high", "Camp Buy Flow", "Logged in", "Home|Cart|Preview|Vouch|Calc|Place", "Completed", "Fails"],
  ["flow_006", "error_case", "user", "P2-high", "high", "Camp Expire", "Logged in", "Home|Cart|Wait Expire|Place", "Reverts price", "Old price"],
  ["flow_006", "auth_boundary", "unauthenticated", "P1-critical", "high", "Unauth Camp", "Logged out", "Home|Cart|Checkout", "Login req", "Proceeds"],
  ["flow_007", "happy_path", "admin", "P1-critical", "high", "Fulfill Flow", "Admin in", "Filter|Review|Confirm|Ship|Deliver", "Completed", "Fails"],
  ["flow_007", "error_case", "admin", "P2-high", "medium", "Skip states", "Admin in", "Filter|Skip to Deliver", "Error msg", "Allowed"],
  ["flow_007", "auth_boundary", "user", "P1-critical", "high", "User Fulfill", "User in", "API update", "403 error", "200 OK"],
  ["flow_008", "happy_path", "admin", "P2-high", "high", "Vouch Flow", "Admin in", "New|Info|AI|Submit", "Active vouch", "Fails"],
  ["flow_008", "error_case", "admin", "P3-medium", "low", "Vouch Dup", "Admin in", "New|Dup code|Submit", "Error msg", "Saved"],
  ["flow_008", "auth_boundary", "user", "P1-critical", "high", "User Vouch", "User in", "Start Flow 008", "403 error", "Proceeds"]
];

data.forEach(d => add(d[0], d[1], d[2], d[3], d[4], d[5], d[6], d[7], d[8], d[9]));

const out = {
  meta: {
    project: "Clothing E-Commerce Management System",
    generated_at: new Date().toISOString(),
    total_test_objectives: tests.length,
    breakdown: {
      by_priority: {
        "P1-critical": tests.filter(t => t.priority === "P1-critical").length,
        "P2-high": tests.filter(t => t.priority === "P2-high").length,
        "P3-medium": tests.filter(t => t.priority === "P3-medium").length,
        "P4-low": tests.filter(t => t.priority === "P4-low").length
      },
      by_actor: {
        "user": tests.filter(t => t.actor === "user").length,
        "admin": tests.filter(t => t.actor === "admin").length,
        "system": tests.filter(t => t.actor === "system").length,
        "unauthenticated": tests.filter(t => t.actor === "unauthenticated").length
      },
      by_scope: {
        "feature": tests.filter(t => t.scope === "feature").length,
        "flow": tests.filter(t => t.scope === "flow").length
      }
    }
  },
  test_objectives: tests.sort((a,b) => a.priority.localeCompare(b.priority))
};

fs.writeFileSync('d:/myData/studio/code/web/IS207/test_objectives.json', JSON.stringify(out, null, 2));
// Output JSON as stdout so it can be captured by the agent
console.log(JSON.stringify(out, null, 2));
