// ─── Mock Data (dev / Storybook / testing) ────────────────────────────────────

import {
  Shirt,
  Pocket,
  StretchHorizontal,
  BedSingle,
  Dumbbell,
  Waves,
  Mountain,
  Bike,
  Swords,
  HandFist,
} from 'lucide-react';

export const MOCK_CATEGORIES = [
  {
    id: '1',
    name: 'Áo thun',
    slug: 'ao-thun',
    icon: Shirt,
  },
  {
    id: '2',
    name: 'Áo sơ mi',
    slug: 'ao-so-mi',
    icon: Shirt,
  },
  {
    id: '3',
    name: 'Quần đùi',
    slug: 'quan-dui',
    icon: Pocket,
  },
  {
    id: '4',
    name: 'Quần dài',
    slug: 'quan-dai',
    icon: StretchHorizontal,
  },
  {
    id: '5',
    name: 'Đồ ngủ',
    slug: 'do-ngu',
    icon: BedSingle,
  },
  {
    id: '6',
    name: 'Đồ tập gym',
    slug: 'do-tap-gym',
    icon: Dumbbell,
  },
  {
    id: '7',
    name: 'Đồ đi biển',
    slug: 'do-di-bien',
    icon: Waves,
  },
  {
    id: '8',
    name: 'Đồ leo núi',
    slug: 'do-leo-nui',
    icon: Mountain,
  },
  {
    id: '9',
    name: 'Đồ chạy xe đạp',
    slug: 'do-chay-xe-dap',
    icon: Bike,
  },
  {
    id: '10',
    name: 'Đồ tập đấu kiếm',
    slug: 'do-tap-dau-kiem',
    icon: Swords,
  },
  {
    id: '11',
    name: 'Đồ tập boxing',
    slug: 'do-tap-boxing',
    icon: HandFist,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max 256GB',
    slug: 'iphone-15-pro-max-256gb',
    price: 34990000,
    originalPrice: 39990000,
    discount: 13,
    image: '/images/products/iphone15.jpg',
    images: ['/images/products/iphone15.jpg'],
    category: { id: '1', name: 'Điện thoại', slug: 'dien-thoai' },
    brand: { id: '1', name: 'Apple', slug: 'apple' },
    rating: 4.8,
    reviewCount: 256,
    sold: 1200,
    stock: 50,
    status: 'active',
    description: 'iPhone 15 Pro Max với chip A17 Pro mạnh mẽ.',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    price: 31990000,
    originalPrice: 33990000,
    discount: 6,
    image: '/images/products/s24ultra.jpg',
    images: ['/images/products/s24ultra.jpg'],
    category: { id: '1', name: 'Điện thoại', slug: 'dien-thoai' },
    brand: { id: '2', name: 'Samsung', slug: 'samsung' },
    rating: 4.7,
    reviewCount: 180,
    sold: 980,
    stock: 30,
    status: 'active',
    description: 'Samsung Galaxy S24 Ultra với bút S Pen tích hợp.',
  },
  {
    id: '3',
    name: 'MacBook Pro M3 14"',
    slug: 'macbook-pro-m3-14',
    price: 49990000,
    originalPrice: 54990000,
    discount: 9,
    image: '/images/products/macbook-m3.jpg',
    images: ['/images/products/macbook-m3.jpg'],
    category: { id: '2', name: 'Laptop', slug: 'laptop' },
    brand: { id: '1', name: 'Apple', slug: 'apple' },
    rating: 4.9,
    reviewCount: 130,
    sold: 560,
    stock: 20,
    status: 'active',
    description: 'MacBook Pro với chip Apple M3 siêu mạnh.',
  },
];

export const MOCK_USER = {
  id: 'u1',
  name: 'Nguyễn Văn A',
  email: 'user@example.com',
  phone: '0901234567',
  avatar: '/images/avatar-placeholder.png',
  role: 'user',
};

export const MOCK_ORDER = {
  id: 'ORD-001',
  status: 'shipping',
  paymentMethod: 'cod',
  paymentStatus: 'unpaid',
  items: [
    {
      productId: '1',
      name: 'iPhone 15 Pro Max 256GB',
      price: 34990000,
      quantity: 1,
      image: '/images/products/iphone15.jpg',
    },
  ],
  subtotal: 34990000,
  shippingFee: 30000,
  discount: 0,
  total: 35020000,
  shippingAddress: {
    name: 'Nguyễn Văn A',
    phone: '0901234567',
    address: '123 Đường ABC',
    ward: 'Phường 1',
    district: 'Quận 1',
    province: 'TP. Hồ Chí Minh',
  },
  createdAt: '2024-01-15T10:30:00Z',
};

export const MOCK_DASHBOARD_STATS = {
  totalRevenue: 125000000,
  totalOrders: 342,
  totalProducts: 185,
  totalUsers: 1240,
  revenueChange: 12.5,
  ordersChange: 8.3,
  productsChange: 3.1,
  usersChange: 15.2,
};
