// ─── Mock Data (dev / Storybook / testing) ────────────────────────────────────

export const MOCK_CATEGORIES = [
  {
    id: '1',
    name: 'Điện thoại',
    slug: 'dien-thoai',
    image: '/images/cat-phone.png',
    productCount: 120,
  },
  {
    id: '2',
    name: 'Laptop',
    slug: 'laptop',
    image: '/images/cat-laptop.png',
    productCount: 85,
  },
  {
    id: '3',
    name: 'Tai nghe',
    slug: 'tai-nghe',
    image: '/images/cat-headphone.png',
    productCount: 60,
  },
  {
    id: '4',
    name: 'Đồng hồ',
    slug: 'dong-ho',
    image: '/images/cat-watch.png',
    productCount: 45,
  },
  {
    id: '5',
    name: 'Phụ kiện',
    slug: 'phu-kien',
    image: '/images/cat-accessories.png',
    productCount: 200,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max 256GB',
    slug: 'iphone-15-pro-max-256gb',
    price: 34990000,
    originalPrice: 39990000,
    discount: 13,
    image: '/images/products/iphone15.jpg',
    images: ['/images/products/iphone15.jpg'],
    category: { id: '1', name: 'Điện thoại', slug: 'dien-thoai' },
    brand: { id: '1', name: 'Apple', slug: 'apple' },
    rating: 4.8,
    reviewCount: 256,
    sold: 1200,
    stock: 50,
    status: 'active',
    description: 'iPhone 15 Pro Max với chip A17 Pro mạnh mẽ.',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    price: 31990000,
    originalPrice: 33990000,
    discount: 6,
    image: '/images/products/s24ultra.jpg',
    images: ['/images/products/s24ultra.jpg'],
    category: { id: '1', name: 'Điện thoại', slug: 'dien-thoai' },
    brand: { id: '2', name: 'Samsung', slug: 'samsung' },
    rating: 4.7,
    reviewCount: 180,
    sold: 980,
    stock: 30,
    status: 'active',
    description: 'Samsung Galaxy S24 Ultra với bút S Pen tích hợp.',
  },
  {
    id: '3',
    name: 'MacBook Pro M3 14"',
    slug: 'macbook-pro-m3-14',
    price: 49990000,
    originalPrice: 54990000,
    discount: 9,
    image: '/images/products/macbook-m3.jpg',
    images: ['/images/products/macbook-m3.jpg'],
    category: { id: '2', name: 'Laptop', slug: 'laptop' },
    brand: { id: '1', name: 'Apple', slug: 'apple' },
    rating: 4.9,
    reviewCount: 130,
    sold: 560,
    stock: 20,
    status: 'active',
    description: 'MacBook Pro với chip Apple M3 siêu mạnh.',
  },
];

export const MOCK_USER = {
  id: 'u1',
  name: 'Nguyễn Văn A',
  email: 'user@example.com',
  phone: '0901234567',
  avatar: '/images/avatar-placeholder.png',
  role: 'user',
};

export const MOCK_ORDER = {
  id: 'ORD-001',
  status: 'shipping',
  paymentMethod: 'cod',
  paymentStatus: 'unpaid',
  items: [
    {
      productId: '1',
      name: 'iPhone 15 Pro Max 256GB',
      price: 34990000,
      quantity: 1,
      image: '/images/products/iphone15.jpg',
    },
  ],
  subtotal: 34990000,
  shippingFee: 30000,
  discount: 0,
  total: 35020000,
  shippingAddress: {
    name: 'Nguyễn Văn A',
    phone: '0901234567',
    address: '123 Đường ABC',
    ward: 'Phường 1',
    district: 'Quận 1',
    province: 'TP. Hồ Chí Minh',
  },
  createdAt: '2024-01-15T10:30:00Z',
};

export const MOCK_DASHBOARD_STATS = {
  totalRevenue: 125000000,
  totalOrders: 342,
  totalProducts: 185,
  totalUsers: 1240,
  revenueChange: 12.5,
  ordersChange: 8.3,
  productsChange: 3.1,
  usersChange: 15.2,
};
